version: "3.8"

services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: khannedy
      MONGO_INITDB_ROOT_PASSWORD: khannedy
      MONGO_INITDB_DATABASE: admin
